### ISSUE TITLE
Testing Issues/Questions 6/29

### ISSUE THREAD

**Issue by jodimward** [esridc/openfda#63] opened 2015-06-29 21:00 UTC
In testing today, I have noted the following issues/questions:

- When on the landing screen, and when I click on a state, then click 'back to overview,' the bar chart box appears but bar chart not loading (may still be in the works)

**Note- when I tested this on my iPhone, the chart did come up.

-When I click on the drop down box for timeline and for status, the box expands across the entire page, rather than maintaining the width of the box.

-Question: is the bar chart title "Recall Enforcement Count by State" an accurate title of what it's representing or should it be renamed? Is something like 'Active Recall Count by State' more appropriate/representative?

**Comment by benheb** [comment] 2015-06-29 22:05
@jodimward can you tell me what browser you're on? I can't reproduce these issues. Anyone else seeing the issue with chart not reloading when going 'back to overview' and the dropdowns going 100% width of the page? @michaelgaigg @gclancy

**Comment by gclancy** [comment] 2015-06-29 22:29
works in Chrome.  

Issues in IE 11 - at least with the chart.  It does not when i open the app, and does not display when i hit "Back to Overview"

**Comment by gclancy** [comment] 2015-06-29 22:31
we should leave the name as -is.  there are both Active and Closed recalls listed - its should be sorted with Active on the top.  The Term "recall enforcement" does come from the FDA website.

We should probably review with users and get additional input before we make any changes.

**Comment by jodimward** [comment] 2015-06-30 12:00
@benheb Gerry is correct- this issue came from testing in IE and I am still unable to see bar chart in this view. The chart is appearing in Firefox and Chrome but the proportion/size of chart varies in each. In Mozilla the chart fills the box, in Chrome, chart does not fill the box. Not a major issue - just wanted to make you aware. See screen grabs below. 

Looks like the drop down box issue was fixed in IE. 

I am losing the 'back to overview' button. It does appear upon entry to the app, but after  clicking on 'show details,' then closing the box and clicking on a new state 'back to overview' does not appear.  If I click on details, then hit the 'back' arrow, 'back to overview' button does appear. This issue was also duplicated in Firefox, and chrome, but was not happening on my iPhone 6.

Population impact is a great add! Looks great in all browsers tested but on iPhone, the population number is appearing without commas

![uploads/6713bc39-9c10-4838-a529-11857ca441b8/FDA bar chart- Chrome View.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6713bc39-9c10-4838-a529-11857ca441b8%2FFDA+bar+chart-+Chrome+View.png)

![uploads/561f6b46-c183-4a76-9559-bb73d556cdd4/FDA bar chart- Firefox View.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F561f6b46-c183-4a76-9559-bb73d556cdd4%2FFDA+bar+chart-+Firefox+View.png)

**Comment by benheb** [comment] 2015-07-01 19:54
I think these are all resolved now, closing.

**Closed by benheb** 2015-07-01 19:54 UTC
Labels: 0 - Backlog
